name: 'Tweet screenshot bot'
on: [push]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        id: tweet
        uses: snow-actions/tweet@v1.1.1
        env:
           CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
           CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
           ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
           ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          with:
            status: |
              hi this is @amtrolling_bot
           media_paths: |
             shot.png

       - run: echo ${{ steps.tweet.outputs.response }}
    
